#!/bin/sh
# File generated by ocamlbuild

cd /Users/noahzweben/Desktop/Columbia/CS2017/PLT/Ballr/Ballr_helloworld

rm -f test_scanner.ml
# Also clean the script itself
rm -f /Users/noahzweben/Desktop/Columbia/CS2017/PLT/Ballr/Ballr_helloworld/_build/sanitize.sh
